Parallel rspec tests (#519)
* parallel tests

* space

* no space

* remove comment

* no more husky

* no husky

* fix .rspec

* coderabbit review feedback

* lint

* updates

* bundle install

* bundle update

* no set -e

* parallel:migrate

* renamed github actions workflows

* try again

* update simplecov

* AUTH_SECRET

* workflow

* config.secret_key_base = ENV[AUTH_SECRET]

diff --git a/.github/workflows/backend-ci.yml b/.github/workflows/backend-ci.yml
--- a/.github/workflows/backend-ci.yml
+++ b/.github/workflows/backend-ci.yml
@@ -1,4 +1,5 @@
-name: Rails API CI
+name: Rails API
+
 on:
   push:
     branches:
@@ -33,9 +34,13 @@ env:
   CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
 
 jobs:
-  rspec:
+  parallel-tests:
     runs-on: ubuntu-latest
-
+    strategy:
+      matrix:
+        group: [1, 2, 3, 4]
+      max-parallel: 4
+    name: RSpec parallel group ${{ matrix.group }}/4
     services:
       postgres:
         image: postgres:16.3
@@ -66,18 +71,53 @@ jobs:
         run: bundle check || bundle install
         working-directory: ./backend
 
-      - name: Prepare database
-        run: bundle exec rake db:create db:schema:load --trace
+      - name: "Runtime cache: restore"
+        uses: actions/cache/restore@v4
+        id: cache-restore
+        with:
+          key: runtime-cache-all
+          path: backend/tmp/parallel_runtime_rspec.log
+
+      - name: Setup database
+        run: |
+          bundle exec rake parallel:create
+          bundle exec rake parallel:migrate
+          bundle exec rake parallel:prepare
         working-directory: ./backend
 
       - name: Run Rspec Tests
         run: |
-          bundle exec rspec --format RspecJunitFormatter --out test-results/rspec/results.xml
-          echo "Exit code: $?"
-        continue-on-error: true
+          mkdir -p tmp/parallel_runtime_rspec
+          if [ -f "tmp/parallel_runtime_rspec.log" ]; then
+            bundle exec parallel_rspec -n 4 --group-by runtime --only-group ${{ matrix.group }} --verbose
+          else
+            bundle exec parallel_rspec -n 4 --group-by filesize --only-group ${{ matrix.group }} --verbose
+          fi
         working-directory: ./backend
         env:
+          AUTH_SECRET: ${{ secrets.AUTH_SECRET}}
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+          RECORD_RUNTIME: "true"
+
+      - name: "Runtime cache: clear chunk"
+        shell: bash
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          cd backend
+          gh extension install actions/gh-actions-cache
+          gh actions-cache delete runtime-cache-${{ matrix.group }} --confirm || true
+          mkdir -p tmp/parallel_runtime_rspec
+          if [ -f "tmp/parallel_runtime_rspec.log" ]; then
+            mv tmp/parallel_runtime_rspec.log tmp/parallel_runtime_rspec/${{ matrix.group }}.log
+          fi
+        continue-on-error: true
+
+      - name: "Runtime cache: store chunk"
+        uses: actions/cache/save@v4
+        with:
+          key: runtime-cache-${{ matrix.group }}
+          path: backend/tmp/parallel_runtime_rspec
 
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
@@ -91,7 +131,7 @@ jobs:
         if: ${{ !cancelled() }}
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
-          files: 'backend/coverage/.resultset.json,backend/coverage/index.html'
+          files: 'backend/coverage/.resultset.json,backend/coverage/index.html,backend/coverage/lcov.info'
           flags: rspec
           name: codecov-umbrella
           verbose: true
@@ -107,6 +147,57 @@ jobs:
 
       - name: List coverage directory
         run: ls -la backend/coverage
+
+
+  store-runtime:
+    runs-on: ubuntu-latest
+    needs: parallel-tests
+    steps:
+      - name: "Runtime cache: load chunk 1"
+        uses: actions/cache/restore@v4
+        with:
+          key: runtime-cache-1
+          path: backend/tmp/parallel_runtime_rspec
+
+      - name: "Runtime cache: load chunk 2"
+        uses: actions/cache/restore@v4
+        with:
+          key: runtime-cache-2
+          path: backend/tmp/parallel_runtime_rspec
+
+      - name: "Runtime cache: load chunk 3"
+        uses: actions/cache/restore@v4
+        with:
+          key: runtime-cache-3
+          path: backend/tmp/parallel_runtime_rspec
+
+      - name: "Runtime cache: load chunk 4"
+        uses: actions/cache/restore@v4
+        with:
+          key: runtime-cache-4
+          path: backend/tmp/parallel_runtime_rspec
+
+      - name: "Runtime cache: combine chunks"
+        run: |
+          mkdir -p backend/tmp
+          if [ ! -f "backend/tmp/parallel_runtime_rspec/1.log" ] || [ ! -f "backend/tmp/parallel_runtime_rspec/2.log" ] || [ ! -f "backend/tmp/parallel_runtime_rspec/3.log" ] || [ ! -f "backend/tmp/parallel_runtime_rspec/4.log" ]; then
+            echo "Error: Missing runtime logs"
+            exit 1
+          fi
+          cat backend/tmp/parallel_runtime_rspec/* > backend/tmp/parallel_runtime_rspec.log
+          cat backend/tmp/parallel_runtime_rspec.log
+      - name: "Runtime cache: clear"
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          gh extension install actions/gh-actions-cache
+          gh actions-cache delete runtime-cache-all --confirm
+        continue-on-error: true
+      - name: "Runtime cache: store"
+        uses: actions/cache/save@v4
+        with:
+          key: runtime-cache-all
+          path: backend/tmp/parallel_runtime_rspec.log
 
   audit:
     defaults:
